### ISSUE TITLE
Errors trying to use cmake

### ISSUE THREAD

**Issue by cristian-ilies-vasile** [jwinarske/pthreads4w#4]
Hello,
I try to compile pthreads4w, using latest cmake version gui versions.
I chose MinGW Makefiles from dropdown menu.

And i get the following errors:

ERROR"unknown" not supported in version.rc

CMake Error at CMakeLists.txt:108 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:134 (shared_lib)

CMake Error at CMakeLists.txt:125 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:138 (static_lib)

**Comment by jwinarske** [comment]
Hi @cristian-ilies-vasile 

There isn't any base MinGW support in master yet.  @bscottm has an outstanding PR for MinGW you might look at in the interim.  Once he can get it to pass the health gate I'll take a look at it.

**Comment by bscottm** [comment]
@cristian-ilies-vasile: The short answer is, "Don't!" Use the `pthreads` support already available in the MinGW-W64. Use this library iff your target is Windows and Visual C/Studio.
