### ISSUE TITLE
Default build type is set to "MinSizeRel" but "Debug" is used

### ISSUE THREAD

**Issue by upnplib** [jwinarske/pthreads4w#6]
I find **MinSizeRel** as default Build Type with:

    PS> cmake -S . -B build -D BUILD_TESTING=OFF
    -- Building for: Visual Studio 16 2019
    -- No build type specified, defaulting to MinSizeRel.
    -- Generator ......... Visual Studio 16 2019
    -- Build Type ........ MinSizeRel
            --- snip ---

but with building the above configuration I get Build Type **Debug** instead:

    PS> cmake --build build
    PS> Get-ChildItem .\build\Debug\

        Directory: C:\Users\ingo\devel\pthreads4w\build\Debug

    Mode                 LastWriteTime         Length Name
    ----                 -------------         ------ ----
    -a---          08/09/2021    10:30         235544 libpthreadVC3d.lib
    -a---          08/09/2021    10:30         118784 libpthreadVC3d.pdb
    -a---          08/09/2021    10:30          55296 libpthreadVCE3d.pdb
    -a---          08/09/2021    10:30         244170 libpthreadVSE3d.lib
    -a---          08/09/2021    10:30         118784 libpthreadVSE3d.pdb
    -a---          08/09/2021    10:30         136704 pthreadVC3d.dll
    -a---          08/09/2021    10:30          20490 pthreadVC3d.exp
    -a---          08/09/2021    10:30         696936 pthreadVC3d.ilk
    -a---          08/09/2021    10:30          34898 pthreadVC3d.lib
    -a---          08/09/2021    10:30         847872 pthreadVC3d.pdb
    -a---          08/09/2021    10:30         139264 pthreadVSE3d.dll
    -a---          08/09/2021    10:30          20491 pthreadVSE3d.exp
    -a---          08/09/2021    10:30         687736 pthreadVSE3d.ilk
    -a---          08/09/2021    10:30          35132 pthreadVSE3d.lib
    -a---          08/09/2021    10:30         864256 pthreadVSE3d.pdb

Also configuring explicitly **MinSizeRel** with:

    cmake -S . -B build -D BUILD_TESTING=OFF -D CMAKE_BUILD_TYPE=MinSizeRel

does not help. I only get the **Debug** build but I need a *Release* one.

**Comment by jwinarske** [comment]
Have you looked at https://github.com/jwinarske/pthreads4w/blob/cmake/appveyor.yml ?

**Comment by upnplib** [comment]
As shown in https://github.com/jwinarske/pthreads4w/blob/cmake/appveyor.yml the generator `NMake Makefiles` have to be used. With default Visual Studio build generator `Visual Studio 16 2019` is used. Using the correct generator fixes the issue.
